# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.1
group=cjminecraft.doubleslabs
java_version=17

# Common
minecraft_version=1.20.1
mod_name=DoubleSlabs
mod_author=CJMinecraft01, Mysticpasta1
mod_id=doubleslabs
license=GNU GPLv3
credits=Mysticpasta1 for 1.20.1 port
description=Allows different slab types to be placed on top of each other.
minecraft_version_range=[1.20.1, 1.21)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.4.0
forge_loader_version_range=[47,)
forge_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

