@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cjminecraft.doubleslabs.fabric.mixin;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;