@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cjminecraft.doubleslabs.fabric.mixin.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;