@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cjminecraft.doubleslabs.fabric.common;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;