@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cjminecraft.doubleslabs.fabric.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;