@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cjminecraft.doubleslabs.neoforge.common.init;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;